cross-service transactions implementation
matrixbotio/rmqworker-lib pull request #105
Opened 2022-07-04 20:38 UTC by NikitaZhdanov

2022-07-04 20:39 UTC, NikitaZhdanov commented on consts.go
> -	publishMaxAttempts                   = 3
Removed as not used

2022-07-05 01:16 UTC, Sagleft commented on structs.go
> +	CSTX               CSTX
в принципе, не очень понятно что это. может `CrossServiceTransaction` хотя бы в имени поля

2022-07-05 01:16 UTC, Sagleft requested changes
имя поля

2022-07-06 12:49 UTC, NikitaZhdanov commented on structs.go
> +	CSTX               CSTX
Поменял имя у типа в итоге, так мне кажется будет более понятно, чем в имени поля

2022-07-07 11:31 UTC, Sagleft approved these changes

2022-07-07 14:16 UTC, KaMeHb-UA approved these changes

2022-07-07 14:16 UTC, merged