Change log to callback
matrixbotio/rmqworker-lib pull request #112
Opened 2022-07-30 15:10 UTC by Sagleft

2022-07-31 11:13 UTC, NikitaZhdanov requested changes

2022-07-31 11:13 UTC, NikitaZhdanov commented on structs.go
> +type LogCallbacks struct {
не хватает `logLog` (хоспади кто ж додумался так уровень логирования назвать, а?, везде ж этот уровень info называется), `logWarn` и `logCritical`

лучше сделать сразу, чтобы потом не было breaking change

2022-08-04 12:50 UTC, Sagleft commented on structs.go
> +type LogCallbacks struct {
вроде Влад так назвал )

нет, надо вообще вернуть обратно логгер. хоть это и не лучший вариант. захотим либу где-то сменить, опять в каждой менять.
но тут, если оставлять callback'и, то нельзя управлять уровнем логов этой либы

2022-08-04 13:14 UTC, NikitaZhdanov commented on structs.go
> +type LogCallbacks struct {
Разве нельзя управлять? Ты пробовал? Я вот с callback не пробовал, поэтому не знаю, может и будет работать, особенно с анонимными функциями непонятно, нужно тестить

2022-08-04 17:52 UTC, Sagleft commented on structs.go
> +type LogCallbacks struct {
ну функция, которая передается к rmq handler в качетсве callback, создается, допустим, на core.
а значит в core будет выполнен logger.Error(...), например. а значит и с package в core это будет......

на core еще ладно. я могу объявить `LOG_LEVEL_TRANSPORT`.
но на marketdata и в trade на пакеты всё не разделено...

2022-08-04 18:25 UTC, Sagleft commented on structs.go
> +type LogCallbacks struct {
есть еще вариант перед логированием проверять os.Getenv("LOG_LEVEL_RMQ") в callback'е.
но это наверно костыль

2022-08-04 19:17 UTC, Sagleft commented
просто сменил либу логера, так будет легче

2022-08-05 04:45 UTC, NikitaZhdanov approved these changes

2022-08-05 06:13 UTC, KaMeHb-UA approved these changes

2022-08-05 06:13 UTC, merged