CSTX nacks
matrixbotio/rmqworker-lib pull request #113
Opened 2022-08-05 19:55 UTC by alex-dwt

2022-08-06 19:00 UTC, NikitaZhdanov requested changes

2022-08-06 19:00 UTC, NikitaZhdanov commented on tests/cstx_test.go
> +package tests
а для чего этот файл?

2022-08-06 19:00 UTC, NikitaZhdanov commented on structs.go
> +	AckNum    int32
для чего изменение типа?

2022-08-06 19:00 UTC, NikitaZhdanov commented on docker-compose.yml
> +services:
а почему не добавил в compose сервисы, которые используются для интеграционных тестов?

2022-08-06 19:00 UTC, NikitaZhdanov commented on cmd/consumer/main.go
> +package main
почему корневая директория называется `cmd`?
я так понимаю тут только интеграционные тесты, может так и назвать `integration-tests`?

2022-08-06 19:00 UTC, NikitaZhdanov commented on Makefile
> +	go run ./cmd/producer/...
```suggestion
	go run ./cmd/producer/...

```

2022-08-06 19:00 UTC, NikitaZhdanov commented on .env
> +COMPOSE_PROJECT_NAME=rmqworker-lib
переименуй файл `.env` в `example.env` плз

2022-08-06 19:00 UTC, NikitaZhdanov commented on .env
> +RABBITMQ_PASS=example
```suggestion
RABBITMQ_PASS=example

```

2022-08-06 19:00 UTC, NikitaZhdanov commented on cmd/consumer/main.go
> +		log.Printf("Finishing")
используй, пожалуйста, логгер из библиотеки `go-common-lib`

2022-08-06 19:00 UTC, NikitaZhdanov commented on cmd/cstx/main/main.go
> +
```suggestion
```

2022-08-06 19:00 UTC, NikitaZhdanov commented on cmd/cstx/service1/main.go
> +
```suggestion
```

2022-08-06 19:00 UTC, NikitaZhdanov commented on cmd/cstx/main/main.go
> +package main
переименуй плз файл в coordinator.go

2022-08-06 19:00 UTC, NikitaZhdanov commented on cstx.go
> +	cstxAcksMap = make(map[string][]CSTXAck, 0)
а для чего это?

2022-08-06 19:00 UTC, NikitaZhdanov commented on cmd/handler.go
> +		//Logger:                  logger.NewLogger(myLogger{}, "host", "source", "1"),
плз удали закомментированый код

2022-08-06 19:00 UTC, NikitaZhdanov commented on structs.go
>  	Type    string // ack or nack
Что-то я не вижу в итоге реализации nack
Вот в этом поле от одного из участников транзакции придет `nack` и это нужно обработать: отменить транзакцию (метод awaitRequiredAcks должен будет вернуть false)

2022-08-06 19:00 UTC, NikitaZhdanov commented on cmd/cstx/main/main.go
> +package main
а директорию - в тип интеграционного теста, сейчас это "successful" flow, насколько я понял, нужно еще добавить интеграционный тест, который будет симулировать "nack"

2022-08-06 19:03 UTC, alex-dwt commented on tests/cstx_test.go
> +package tests
тут будут интеграционные тесты, а именно     на     CSTX,      ну и вообще любые интеграционные тесты в будущем

2022-08-06 19:04 UTC, alex-dwt commented on structs.go
> +	AckNum    int32
можешь ревертнуть и   запустить    main & service1
там не приводиться к .(int) была паника,,   написано было что там лежит int32   типа того
где и что я не разбирался, в хеждерах чтоли

2022-08-06 19:04 UTC, alex-dwt commented on docker-compose.yml
> +services:
для интеграционных тестов - нужен только рабит такто
но пока еще и тестов нету т.к. cstx не работает..

2022-08-06 19:05 UTC, alex-dwt commented on Makefile
> +	go run ./cmd/producer/...
а че тут..

2022-08-06 19:05 UTC, alex-dwt commented on cmd/cstx/service1/main.go
> +
не нужно плз копаться в   ./cmd/  папке
это все для тестов и для локальной разработки

2022-08-06 19:06 UTC, alex-dwt commented on cmd/cstx/main/main.go
> +package main
когда будут тесты интеграционные писаться, тогда и добавим
пока нету, т..к. нихя не работает)

2022-08-06 19:07 UTC, alex-dwt commented on cmd/cstx/main/main.go
> +package main
---переименуй плз файл в coordinator.go---
опятьтаки, это для тестов, локально,  но что бы всем было более понятнее в теории можно и в coordinator

2022-08-06 19:08 UTC, alex-dwt commented on cmd/handler.go
> +		//Logger:                  logger.NewLogger(myLogger{}, "host", "source", "1"),
опятьтаки
1 - папка cmd - плз  не нужно тут копаться.
2 - скорее на будущее - если код закоментирован, значт он как бэ нужен,   чем он мешаетто

2022-08-06 19:09 UTC, alex-dwt commented on structs.go
>  	Type    string // ack or nack
реализации nack  тут нету, т.к.  я впринципе не разобрался   работает ли весь CSTX  впрниципе и как он работает
пока вижу что ты ни разу код не запускал
поэтому итеративно
верно ли  написан    main & service1  - мне нужно понять
баг лучше пофиксить с лишники cstx очередями
а уж потом можно и до nack

2022-08-06 19:11 UTC, alex-dwt commented on structs.go
>  	Type    string // ack or nack
а ну и конечно
при мерже сейчас - не закрывтаь таску
а сделать потом еще раз опять этуже самую ветку на этот же таск

не, ну можно и не мержить пока,   как бэ не суть

но мержить можно - т.к.  сдесь сделана какаято часть работы, хоть и не nack

2022-08-06 19:12 UTC, alex-dwt commented on cmd/consumer/main.go
> +package main
неверно
сли еще не смотрел https://github.com/golang-standards/project-layout
то плз изучи

src и т.п. и main.go в корне - все неверно

cmd & internal & pkg - это в 2х словах

2022-08-06 19:41 UTC, alex-dwt commented on .env
> +COMPOSE_PROJECT_NAME=rmqworker-lib
почему и в чем прикол этого ?
я могу аргументировать почему  .env   --- т.к.   docker-compose его с ходу подхватывает, а это очень хорошо
каковы аргументы    example.env ?

2022-08-06 19:42 UTC, alex-dwt commented on cmd/consumer/main.go
> +		log.Printf("Finishing")
1 - сдесь лог врпниипе не нужен
2 -  я его использовал вроде , - он ничего не писал, наверное не успевыает отработать

ну вприцнипе еще раз гляну что там за  go-common-lib  и   будет ли этот лог туда отписываться

2022-08-06 19:44 UTC, alex-dwt commented on cstx.go
> +	cstxAcksMap = make(map[string][]CSTXAck, 0)
ты не запускал   свой код ни разу, я так понял.
т.к. он не рабочий изза этой строчки.

panic  сразу же при первом добавлении туда (т.к. мапу нужно такто инициализировать перед тем как юзать)

2022-08-07 08:58 UTC, Sagleft commented on structs.go
> +	AckNum    int32
получение header из rmq? да, вроде есть какой-то прикол такой. в int можно сконвертировать так
```
int(val.(int32))
```

2022-08-07 09:00 UTC, Sagleft commented on cmd/handler.go
> +		//Logger:                  logger.NewLogger(myLogger{}, "host", "source", "1"),
это мы проходили xD Никита не даст оставить комментарии

2022-08-07 09:09 UTC, alex-dwt commented on structs.go
> +	AckNum    int32
а в чем проблема с int32 впринципе?   не хватит вместимости что бы записать  AckNum  ?
я уже сделал int32  и все работает - т.к. изначально была проблема, и я ее так пофиксил, в int32 не вижу проблем
если нету явных аргументов против int32 то предлагаю так и оставить,  или плз пофиксите сами как считаете нужным

2022-08-07 09:13 UTC, alex-dwt commented on cmd/handler.go
> +		//Logger:                  logger.NewLogger(myLogger{}, "host", "source", "1"),
это не серьезно.

рассказываю - баг в cstx. там Logger  nil   вызывает ошибку.
если кинуть в cstx   неверный json,    то он обращается к логгеру, и паника

т.о. я фиксил этой строчкой, сетав логгер здесь --- но изначально проблема гдето в другом месте, в самой cstx,  

а закоментил я ее сейчас т.к.   с нею   тогда вообще почему логи подругому пишуться (не verbose)

т.о.  иногда я запускаю код с закоменченной строчкой, иногда нет

впринцйипе  если ктото поправит баг с паникой, что я выше описал - то эта строчка не нужна будет
сейчас - нужна

2022-08-07 09:20 UTC, alex-dwt commented on cmd/handler.go
> +		//Logger:                  logger.NewLogger(myLogger{}, "host", "source", "1"),
а
и  также это  /cmd
как и выше замечал, не нужно вылизывать код в  /cmd/   когда  у нас этот репозиторий - библиотека, и папка  cmd  здесь вообще   для тестовых экзешников так сказать.

2022-08-07 13:58 UTC, NikitaZhdanov commented on structs.go
>  	Type    string // ack or nack
@alex-dwt в названии PR сказано "CSTX nacks", поэтому такие вопросы )

2022-08-07 14:04 UTC, NikitaZhdanov commented on .env
> +COMPOSE_PROJECT_NAME=rmqworker-lib
у нас принято коммитить example.env
.env каждый локально у себя делает при необходимости со своими настройками

2022-08-07 14:07 UTC, NikitaZhdanov commented on cmd/consumer/main.go
> +		log.Printf("Finishing")
Если уж ты коммитишь cmd и тестируешь локально, то лучше все-таки придерживаться каких-то общих правил, чтобы те кто читает код (и будет возможно в будущем переиспользовать его для локальных тестов) было проще.

Плюс в данном случае ты знакомишься с нашей либой go-common-lib. В этой либе есть метод awaitLoggers, который собственно перед завершением приложения дожидается пока все логгеры отработают.

2022-08-07 14:17 UTC, NikitaZhdanov commented on cmd/handler.go
> +		//Logger:                  logger.NewLogger(myLogger{}, "host", "source", "1"),
> рассказываю - баг в cstx. там Logger nil вызывает ошибку. если кинуть в cstx неверный json, то он обращается к логгеру, и паника

ну, логгер - обязательный параметр, и баг лишь в том, что не проверяется этот параметр при инициализации

то что у тебя не пишется verbose - это потому что у логгера дефолтный уровень логирования - info, если нужен verbose, то нужно в параметрах при инициализации нового логгера отправить уровень логирования verbose (0)

2022-08-07 14:19 UTC, NikitaZhdanov commented on cstx.go
> +	cstxAcksMap = make(map[string][]CSTXAck, 0)
может тогда инициализировать мэп сразу в глобальной переменной:
```
var cstxAcksMap = make(map[string][]CSTXAck, 0)
```

и избавиться от init метода?

2022-08-07 14:28 UTC, NikitaZhdanov requested changes

2022-08-07 14:28 UTC, NikitaZhdanov commented on cmd/cstx/coordinator/main.go
> +	res, err := transaction.Commit()
координатор написан корректно, единственное что - он не должен делать коммит по-идее, если сам не выполняет какие-то действия в рамках этой транзакции.

Но для тестов будем считать, что тоже что-то пишет в БД в рамках транзакции.

2022-08-07 14:28 UTC, NikitaZhdanov commented on cmd/cstx/service1/main.go
> +func main() {
сервис написан корректно с точки зрения cstx

2022-08-07 17:24 UTC, alex-dwt commented on .env
> +COMPOSE_PROJECT_NAME=rmqworker-lib
---.env каждый локально у себя делает при необходимости со своими настройками

ну ващет ладно, это верно.
просто думал впринципе нечего тут настраивать  индивидуально, и один .env  всем подойдет
пока там нету какихто проброски портов настроек,,

2022-08-07 17:26 UTC, alex-dwt commented on cmd/consumer/main.go
> +		log.Printf("Finishing")
ну впринципе согласен.
конечно   т.к.  cmd   ну тут ваще зауши притянут в библилотеку, там можно и говно писать и через .log всмысле
и не парится с какимито  go-common-lib  , т.к. я в них ваще еще не разбирался, поэтому и не заюзал
но можно глянуть уж сразу че там

2022-08-07 17:30 UTC, alex-dwt commented on cstx.go
> +	cstxAcksMap = make(map[string][]CSTXAck, 0)
хм
а я чето не проверил так
думал что var   нельзя будет инициализировать сразу через make()     
хм, видимо чето напутал,, помню ж както есть кейсы когда  var  глобальный нельзя инициализировать,  
тут да, можно без init

2022-08-08 20:53 UTC, NikitaZhdanov approved these changes

2022-08-09 16:24 UTC, Sagleft approved these changes

2022-08-09 16:25 UTC, merged