Add mock to CSTX
matrixbotio/rmqworker-lib pull request #130
Opened 2022-10-30 16:51 UTC by alex-dwt

2022-10-30 20:22 UTC, Sagleft approved these changes

2022-10-31 10:13 UTC, NikitaZhdanov commented on pkg/cstx/cstx.go
> +type CSTX interface {
а зачем тут интерфейс, а не в сервисах, использующих CSTX?

2022-10-31 10:13 UTC, NikitaZhdanov approved these changes

2022-10-31 18:06 UTC, alex-dwt commented on pkg/cstx/cstx.go
> +type CSTX interface {
ага. давай вспомню.
знач
1 это типа у нас внутренняя либа, на котоорую все микросервисы типа повязаны внутрянкой, т.е. юзают cstx rnq и т.п.
2 cstx по факту такая единсвенная в своем роде структура, блин, кароч как бы объяснить - она мне вообще не упала ни в одном микросервисе и их зависимостях, т.е. я ее ваще не встраивал бы в свои юзкейсы (т.к. по "бизнес" логике юзкейса оно ваще не нужно ниразу),,,,, но т.к. приходится! изза ну такой вот нашей приблуды с кросс-транзакциями, то мне реально приходится прям прибивать гвоздями сразу вот эту нашу cstx ну туда по месту в мои юзкейсы,,,,,  и как и сказал - ниче плохого нету, т.к. смотри пункт (1)
3 чтобы сделать тут же в этом пакете сразу и мок на cstx
4 т.о. учитвая (3) нам не придется делать копипасту в каждом микросервисе на 2 идинтичных файла (Интерфейс + мок), а по факту мы это все положили сразу тут же в библиотеке.   кстати,,, не "в каждом микросервисе" - а в каждом юзкейсе! т.е. если бы как ты и сказал интффейс на эту штуку ложит в микросервисах - то там придется в каждом юзкейсе практически.. во как..

2022-10-31 18:46 UTC, NikitaZhdanov commented on pkg/cstx/cstx.go
> +type CSTX interface {
Чёт не убедил, давай-ка для консистентности все же сделаем в конечных сервисах интерфейс

2022-10-31 18:46 UTC, NikitaZhdanov requested changes
Интерфейс

2022-11-01 19:54 UTC, alex-dwt commented on pkg/cstx/cstx.go
> +type CSTX interface {
блин, лан, последнее 
я чет не понял
вплане - а в чем проблема что тут лежил мок для либы ? ну вот лежит он  и лежит
интерфейс для того что бы мок создать

наша библиотека - чего бы не положить ?
т.о. чето непонятно, почему нельзя

2022-11-01 20:05 UTC, NikitaZhdanov commented on pkg/cstx/cstx.go
> +type CSTX interface {
У тебя в сервисе интерфейсы и моки даже внутри приложения генерятся и могут повторяться, я не понимаю почему тут по-другому, отсутствие одинакового подхода сбивает с толку

2022-11-02 17:55 UTC, alex-dwt commented on pkg/cstx/cstx.go
> +type CSTX interface {
----У тебя в сервисе интерфейсы и моки даже внутри приложения генерятся и могут повторяться
повторятся они не могут
в каждом сервисе/юзкейсе - будут уникальные зависимости-интерфейсы, хотя вообщето частично будут пересекаться

как и говорил
cstx - чиста "инфраструктурная" херотень.   она не нужна в юзкейсах, она не приносит никакой логики так сказать.
поэтому ее и лучше не выносить в юзкейсы, а сразу снаружи и подключать, т.о. и лучше ее порлождит в тойже rmq либе, т.к. как и сказал это чисто херабора rmq либы, логично ее там и держать

2022-11-02 20:25 UTC, NikitaZhdanov approved these changes

2022-11-03 17:59 UTC, alex-dwt commented
-(
удалять счас cstx из marketplace,, тока вчера туда перекопировал ахахаахах
ну смотри, я не заставлял))

но как и сказал, я не думаю что поспешил выносить сюда интерфейс с моком, т.к. полюбасу он попрет в 100500 микросервисах

2022-11-04 16:13 UTC, merged