Task-134 Syncrpchandler: add
matrixbotio/rmqworker-lib pull request #135
Opened 2022-12-10 15:52 UTC by alex-dwt

Придется походу еще   прикручивать CSTX  сюдаже,   но это следуюищими ветками,,,,   т.к. раскуривать нужно....

Вот так отрабатывает тест интеграционный - выкладываю картинки что бы вы заценили похоже на правду или нет, и как все работает.

[pic1 !!!!!!!!!](https://ibb.co/T2gG9V5)
[pic2 !!!!!!!!!!!](https://ibb.co/zbgPNqG)

2022-12-10 18:47 UTC, NikitaZhdanov requested changes

2022-12-10 18:47 UTC, NikitaZhdanov commented on pkg/syncrpc/handler.go
> +	queueName         string
Response Routing Key и Queue должны быть уникальными для каждого инстанса приложения

В текущей реализации насколько я понимаю это не так

2022-12-10 18:47 UTC, NikitaZhdanov commented on pkg/syncrpc/handler.go
> +		queueName:  fmt.Sprintf("syncrpc:%s:%s", props.ServiceTag, props.ResponsesExchange),
Лучше использовать serviceTag-uuid (так же в Java реализации)

2022-12-12 20:06 UTC, Sagleft approved these changes

2023-01-04 19:52 UTC, NikitaZhdanov requested changes

2023-01-04 19:52 UTC, NikitaZhdanov commented on pkg/syncrpc/execute_request.go
> +		RoutingKey:         h.props.RequestsExchange,
RoutingKey должен задаваться из параметров метода, т.к. он может меняться динамически, ну и он точно != Exchange Name

2023-01-04 19:52 UTC, NikitaZhdanov commented on pkg/syncrpc/responses_consumer.go
> +		//DisableOverflow:            props.DisableOverflow,
plz remove commented code

2023-01-29 12:24 UTC, alex-dwt commented on pkg/syncrpc/handler.go
> +		queueName:  fmt.Sprintf("syncrpc:%s:%s", props.ServiceTag, props.ResponsesExchange),
done

2023-01-29 12:25 UTC, alex-dwt commented on pkg/syncrpc/execute_request.go
> +		RoutingKey:         h.props.RequestsExchange,
done
https://github.com/matrixbotio/rmqworker-lib/pull/135/commits/279eb33f503e400bc710b63d4c6ad279b9496ca8

2023-01-29 15:17 UTC, NikitaZhdanov approved these changes

2023-02-12 10:00 UTC, NikitaZhdanov commented on pkg/syncrpc/handler.go
> +func NewHandler(rmqHandler *rmqworker.RMQHandler, logger *zap.Logger, props HandlerProps) (*Handler, error) {
Вот только сейчас понял, что у нас тут возникает небольшой конфликт в названиях: у нас хендлеры на проекте относятся к обработчикам входящих запросов, а не исходящих.
Мне сейчас нужно сделать обработчик входящих запросов и получается имя handler уже занято
Может переименовать в адаптер?

2023-02-12 16:27 UTC, alex-dwt commented on pkg/syncrpc/handler.go
> +func NewHandler(rmqHandler *rmqworker.RMQHandler, logger *zap.Logger, props HandlerProps) (*Handler, error) {
ну......... ваще ниразу не решение. если чтото гдето занято - то идти чето кудато переименовывать.
это пакет под названием syncrpc.
в нем лежит обцчный сервис, назвал handler  т.к. ну у нем 1! метод -> handle() или типа того.
можно назвать сервис ,, SyncRpcService
но в сервисе если бы хоть 1+ методов было, т.е. побольше - тогда был бы сервисом, а так, нафига его сервисом назхывать.

а пересечения и т.п. с проектом - да в любом случае,    на это нельзя равняться.
библотека живет своей жизнью, и в библиотеке никто не будет пождстраиваться под код проектов.
можно юзать алиасы.

КСАТИТ
нужно   NewHandler    переименовать в    New()  и все. никаких хендлеров. ну как бы.   если тут реальтно тока Handler сохздается,   
то в пакете должен быть только New() один и все.

2023-02-12 16:28 UTC, merged