implement syncrpc handler to handle sync requests
matrixbotio/rmqworker-lib pull request #136
Opened 2023-02-12 12:01 UTC by NikitaZhdanov

rename syncrpc handler to adapter

2023-02-12 16:17 UTC, alex-dwt commented
очень интересно
а почему это стал adapter ?
что он "адаптирует", ну всмысле к чему это "переходник" ?

в моем пониманиии и тогда, и сейчас - это какойто сервис. в моем случае я назвал хендлер, ну можно было и сервис.
адаптеры - это когда ты делаешь адаптеры в своем коде, т.е. берешь   какуюто либу, всмылен поджключаешь через go get, к ней пишешь адаптер, в своем коде, и ок.

сдесь же причем адаптер ?

2023-02-12 16:19 UTC, alex-dwt commented
https://refactoring.guru/ru/design-patterns/adapter/php/example

2023-02-12 16:35 UTC, alex-dwt commented
можно плз както делать пошагово
тут явно 2 комита минимум должно быть

первый - тупое переименование  handler в adapter, через IDE
второе - твои изменеия

т.к. сейчас нету возможности нормально понять что ты тут делал.
т.к. все кучей сливается

2023-02-13 07:28 UTC, NikitaZhdanov commented
@alex-dwt 
1. Переименовал адаптер в сервис
2. Сделал 2 коммита
3. Пофиксил конфликты

2023-02-13 21:47 UTC, alex-dwt commented on pkg/syncrpc/callback_with_response.go
> +		var responseErr *constants.APIError = nil
99.9% что    =nil  это лишнее

т.е. просто 

> var responseErr *constants.APIError

2023-02-13 21:47 UTC, alex-dwt commented on pkg/syncrpc/callback_with_response.go
> +	response, err := callback(h.worker, deliveryHandler)
тут точно ок?
что err проверяется только на 29 строчке а не тут ?

2023-02-13 21:49 UTC, alex-dwt commented on pkg/syncrpc/callback_with_response.go
> +	exchange := h.props.Exchange
не поянтно зачем эта строчка
хотя бы потому что на строчке 20 - ты опять берешь через h.props.Exchange  , а не берешь эту exchange

2023-02-13 21:50 UTC, alex-dwt commented on pkg/syncrpc/callback_with_response.go
> +		if err := h.rmqHandler.SendRMQResponse(
давай писать в одну строчку если оно вмещается в 120, т.к. ну чето ваще несмотриться, учитывая что тут еще в if обернуто

2023-02-13 21:52 UTC, alex-dwt commented on pkg/syncrpc/handler.go
> +			h.callbackWithResponse(&deliveryHandler, h.callback)
а зачем тут ты пробрасываешь h.callback ?
если он и так уже в handler есть ?

там же будт просто   

> 	response, err := h.callback(h.worker, deliveryHandler)

вместо
	

> response, err := callback(h.worker, deliveryHandler)

т.о. это параметр тут не нужно пробрасывать

2023-02-13 21:56 UTC, alex-dwt requested changes
не догоняю зачем ты добавлял этот Handler, ну повидимому он тебе для чегото  нужен не суть
но тогда вопросы:
- а это типа syncrpc тоже?
- даже если да, так давай сделаешь новую подпапку, т.е. пакет типа
/syncrpc/handler/ТУТ
и сюда все запихнешь сове новое что сделал.

обхянсяю - у меня был пакет цельный, и можно было понять по файлам и изучть его

а что теперь делает твой handler с callback тут - для меня загадка.
если эжто что ну не заявзанное на мои файлы - так давай в подпакет выносить\
иначе сбивает

2023-02-13 22:01 UTC, alex-dwt commented
кстати 
и т.о. не нужно делать то что ты делал - переименование Handler в Service.
т.к. оно бюждует в подпакетах.
кстати, т.к. я уже как бы жзаю эту билилотеку, и мне придется менять (хотя если менять на New() то всеравно придется мне переименовывать)

кароч,   не вижу смысла городить  все в одном пакете, если   можно сделать все в подпакетах, и только всем легче будет

2023-02-14 18:15 UTC, NikitaZhdanov commented on pkg/syncrpc/callback_with_response.go
> +	response, err := callback(h.worker, deliveryHandler)
Да, тут ошибка прокидывается дальше в ответ

2023-02-14 18:17 UTC, NikitaZhdanov commented on pkg/syncrpc/callback_with_response.go
> +	exchange := h.props.Exchange
изменил 20-ю строчку

2023-02-15 09:18 UTC, Sagleft commented on pkg/syncrpc/handler/syncrps_test.go
> +	deliveryHandler := dependencies2.NewMockRMQDeliveryHandler(t)
кажись не хотели применять номера в алиасах

2023-02-15 09:19 UTC, Sagleft approved these changes

2023-02-16 19:51 UTC, alex-dwt approved these changes

2023-02-16 20:15 UTC, merged