Exchange name to task
matrixbotio/rmqworker-lib pull request #25
Opened 2021-12-03 13:03 UTC by Sagleft

2021-12-03 13:40 UTC, NikitaZhdanov requested changes

2021-12-03 13:40 UTC, NikitaZhdanov commented on publishing.go
> +	responseRoutingKey ...string,
Why ...string?
It's confusing that you can pass 2or more routingKeys in the parameter, but only first will be used

2021-12-03 13:40 UTC, NikitaZhdanov commented on publishing.go
> +func (r *RMQHandler) RMQPublishToExchange(
Publish to queue method has a task type as parameter.
Here it's a list of params.
Please make code more consistent and use similar parameter input

2021-12-03 15:35 UTC, Sagleft commented on publishing.go
> +	responseRoutingKey ...string,
так первый routing, второй response routing. более чем понятно

2021-12-03 15:35 UTC, Sagleft commented on publishing.go
> +func (r *RMQHandler) RMQPublishToExchange(
ага и переделывать из-за этого сейчас на всех сервисах? время улучшайзинга еще придет

2021-12-03 21:19 UTC, NikitaZhdanov commented on publishing.go
> +	responseRoutingKey ...string,
Я про responseRoitingKey конкретно

2021-12-04 11:22 UTC, Sagleft commented on publishing.go
> +	responseRoutingKey ...string,
а, про индекс? так это частая практика. добавление необязательного параметра таким образом и взятие 1-ого элемента

2021-12-05 06:03 UTC, NikitaZhdanov commented on publishing.go
> +	responseRoutingKey ...string,
Может и частая, но сбивающая с толку, я бы переделал, @KaMeHb-UA твоё мнение?

2021-12-05 06:03 UTC, NikitaZhdanov commented on publishing.go
> +func (r *RMQHandler) RMQPublishToExchange(
@KaMeHb-UA, твоё мнение?

2021-12-05 17:55 UTC, KaMeHb-UA commented on publishing.go
> +	responseRoutingKey ...string,
@NikitaZhdanov в golang только так и делается, пусть остаётся

2021-12-05 17:57 UTC, KaMeHb-UA approved these changes

2021-12-05 17:57 UTC, KaMeHb-UA commented on publishing.go
> +func (r *RMQHandler) RMQPublishToExchange(
если честно, тут не понял, в чём вообще вопрос возник

2021-12-05 19:40 UTC, NikitaZhdanov commented on publishing.go
> +	responseRoutingKey ...string,
@KaMeHb-UA в смысле только так? А пустая строка? А указатель?

2021-12-05 19:42 UTC, NikitaZhdanov commented on publishing.go
> +func (r *RMQHandler) RMQPublishToExchange(
В методе для публикации сообщения в очередь параметр один - объект

Тут несколько параметров, хотя в принципе методы делают почти одно и то же.

Хотелось бы однообразия

2021-12-05 19:45 UTC, KaMeHb-UA commented on publishing.go
> +	responseRoutingKey ...string,
@NikitaZhdanov, пустая строка — это не опциональный параметр. Честно говоря, наличие обязательного параметра responseRoutingKey и будет сбивать с толку, такое уже я не смогу зааппрувить. Передача указателей на строки — плохая практика, таким в голанге только амазон балуется. Важно понимать, что указатели в голанг — не то же, что и указатели в плюсах, например.

2021-12-05 19:51 UTC, KaMeHb-UA approved these changes

2021-12-05 19:51 UTC, KaMeHb-UA commented on publishing.go
> +func (r *RMQHandler) RMQPublishToExchange(
а, понял, но это действительно уже чисто косметическое улучшение. Мне кажется, это не необходимо для ревью. Можно отдельную задачу на унификацию сигнатур в low priority закинуть

2021-12-05 20:17 UTC, NikitaZhdanov approved these changes

2021-12-05 20:17 UTC, merged

2021-12-06 07:01 UTC, Sagleft commented on publishing.go
> +	responseRoutingKey ...string,
амазону так всё можно xD