Test reinit
matrixbotio/rmqworker-lib pull request #85
Opened 2022-05-09 13:08 UTC by Sagleft

2022-05-09 14:40 UTC, NikitaZhdanov requested changes

2022-05-09 14:40 UTC, NikitaZhdanov commented on workers.go
> +	//for w.awaitMessages {
```suggestion
```

2022-05-10 11:46 UTC, NikitaZhdanov requested changes

2022-05-10 11:46 UTC, NikitaZhdanov commented on workers.go
> +	//}
```suggestion
```

2022-05-10 11:48 UTC, Sagleft commented on workers.go
> +	//}
да там всё и так потом будет удалено. либа полностью обновляется

2022-05-10 12:24 UTC, NikitaZhdanov approved these changes

2022-05-10 12:25 UTC, merged